askme_Mkrtchyan/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from django.conf.urls import url

from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('hot/', hot, name='hot'),
    path('question/<int:pk>/', question, name='question'),
    path('settings/', settings, name='settings'),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('ask/', ask, name='ask'),
    url(r'^tag/(?P<tag_name>.*)/$', tag, name='tag'),
    url(r'^(?P<username>[a-zA-Zа-яА-Я_\-\.0-9]+?)$', profile, name='profile'),
    url(r'^logout/.*?$', logout, name='logout'),
    re_path(r'^/', index),
    url(r'^api/question/(?P<pk>\d+)/like/$',
        login_required(VotesView.as_view(model=Question, vote_type=Like.LIKE)),
        name='question_like'),
    url(r'^api/question/(?P<pk>\d+)/dislike/$',
        login_required(VotesView.as_view(model=Question, vote_type=Like.DISLIKE)),
        name='question_dislike'),
    url(r'^status-change/.*', AnswStatusChange, name = "status-change"),
    url(r'^api/answer/(?P<pk>\d+)/like/$',
        login_required(VotesView.as_view(model=Answer, vote_type=Like.LIKE)),
        name='answer_like'),
    url(r'^api/answer/(?P<pk>\d+)/dislike/$',
        login_required(VotesView.as_view(model=Answer, vote_type=Like.DISLIKE)),
        name='answer_dislike'),
    url(r'^(?P<username>[a-zA-Zа-яА-Я_\-\.0-9]+?)$', profile, name='profile'),
]

app/models.py
from django.conf import settings
import os
from uuid import uuid4
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.utils import timezone
# Create your models here.

from app.managers import *

class User(AbstractUser):
    avatar = models.ImageField(default="static/img/1.jpg", upload_to='static/upload/')
    rank = models.IntegerField(default=0, verbose_name='User rating')

    objects = UserManager()


    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username


class Tag(models.Model):
    title = models.CharField(max_length=15, default='404', verbose_name='Tag')

    objects = TagManager()

    class Meta:
        verbose_name = 'Тэг'
        verbose_name_plural = 'Тэги'
        unique_together = ('title',)

    def __str__(self):
        return self.title



class Like(models.Model):

    LIKE = 1
    DISLIKE = -1

    VOTE_TYPES = ((LIKE, 'Like'), (DISLIKE, 'Dislike'))

    user = models.ForeignKey(User, null=True, verbose_name='Like author', on_delete=models.CASCADE)
    vote = models.SmallIntegerField(verbose_name='is like', default=VOTE_TYPES[0], choices=VOTE_TYPES)

    content_type = models.ForeignKey(ContentType, default=None, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(default=-1)
    content_object = GenericForeignKey()

    objects = LikeManager()

    class Meta:
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'

    def __str__(self):
        return "Like from " + self.user.username
#
#
class Question(models.Model):
    author = models.ForeignKey(User, null=False, verbose_name='Question author', on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, verbose_name='Question date')

    is_active = models.BooleanField(default=True, verbose_name='Question aviability')

    title = models.CharField(max_length=70, verbose_name='Header')
    text = models.TextField(verbose_name='Question full text')

    tags = models.ManyToManyField(Tag, related_name='questions', blank=True, verbose_name='Tags')

    votes = GenericRelation(Like, related_query_name='questions')
    rate = models.IntegerField(default=0, null=False, verbose_name='Rate')

    type = 'question'

    objects = QuestionManager()

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return self.title


class Answer(models.Model):
    author = models.ForeignKey(User, null=False, verbose_name='Answer author', on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now, verbose_name='Answer date')

    question = models.ForeignKey(Question, related_name='answers', verbose_name='Answered question',
                                 on_delete=models.CASCADE)
    text = models.TextField(verbose_name='Answer full text')
    status = models.BooleanField(verbose_name=u"Status", default=False)
    votes = GenericRelation(Like, related_query_name='answers')
    rate = models.IntegerField(default=0, null=False, verbose_name='Rate')

    type = 'answer'

    objects = AnswerManager()


    class Meta:
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'

    def __str__(self):
        return self.text

templates/ask.html
{% extends 'include/base.html' %}

{% block content %}
    {% include 'include/create_question_forms.html' %}
{% endblock content %}

templates/base.html
{% extends "include/base.html" %}
{% load static %}

{% block content %}
    {% include "include/new_questions_header.html" %}

    {% for answer_question_block in page %}
        {% include "include/question_base.html" %}
    {% endfor %}

    {% include "include/pagination.html" %}
{% endblock content %}
{% block like_js %}
    <script src="{% static 'js/like.js' %}"></script>
{% endblock %}

templates/hot.html
{% extends "include/base.html" %}
{% load static %}

{% block content %}
    {% include "include/hot_questions_header.html" %}

    {% for answer_question_block in page %}
        {% include "include/question_base.html" %}
    {% endfor %}

    {% include "include/pagination.html" %}

{% endblock content %}
{% block like_js %}
    <script src="{% static 'js/like.js' %}"></script>
{% endblock %}

templates/login.html
{% extends 'include/base.html' %}

{% block content %}
    {% include 'include/login_forms.html' %}
{% endblock content %}

templates/profile.html
{% extends 'base.html' %}

{% load static %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
        <div class="col-12">
    <div class="page-header">
        <div class="row">
            <div class="col-md-5">
                <h2>{{ user }}</h2>
            </div>
        </div>
    </div>
</div>
    <img class="profile-avatar" src="{{ user.avatar.url }}" style="width: 150px; height: 170px; float: left" alt="">
    <div class="profile-info">
        {% if user.first_name != null %} <h4><i>First name: </i> {{ user.first_name }}</h4> {% endif %}
        {% if user.last_name != null %} <h4><i>Last name: </i> {{ user.last_name }}</h4> {% endif %}
        {% if user.email != null %} <h4><i>Email: </i> {{ user.email }}</h4> {% endif %}
        {% if user != null %} <h4><i>Nick Name: </i> {{ user }}</h4> {% endif %}
        <hr>
        <h4>
            <i>Questions: </i>{{ user.question_set.all | length }}
            <i>Answers: </i>{{ puser.answer_set.all | length }}
        </h4>
    </div>
    <hr>
    <div class="activity">
        <table>
            <tr>
                <th><h3>Questions</h3></th>
                <th><h3>Answers</h3></th>
            </tr>
            <td class="questions">
                {% for q in user.question_set.hottest %}
                    <div class="list-group">
                        <a href="/question/{{ q.id }}/" class="list-group-item">
                            <div class="rate">
                                {% if q.rate <= 0 %}<img class="rate-icon" src="{% static 'img/stats_down.png' %}" alt="">
                                {% else %}
                                <img class="rate-icon" src="{% static 'img/stats_up.png' %}" alt="">
                                {% endif %}
                                {{ q.rate }}
                            </div>
                            <div class="header">
                                <h4 class="list-group-item-heading">{{ q.title }}</h4>
                                <h5>{{ q.date }}</h5>
                            </div>
                            {% for tag in q.tags.all %}
                                <span class="label label-danger">{{ tag.title }}</span>
                            {% endfor %}
                        </a>
                    </div>
                {% endfor %}
            </td>
            <td>
                {% for a in user.answer_set.hottest %}
                    <div class="questions list-group">
                        <a href="/question/{{ a.question_id }}/#{{ a.id }}" class="list-group-item">
                            <div class="rate">
                                {% if a.rate <= 0 %}<img class="rate-icon" src="{% static 'img/stats_down.png' %}" alt="">
                                {% else %}
                                <img class="rate-icon" src="{% static 'img/stats_up.png' %}" alt="">
                                {% endif %}
                                {{ a.rate }}
                            </div>
                            <h4>{{ a.question.title }}</h4>
                            <hr>
                            <p>{{ a.text }}</p>
                        </a>
                    </div>
                {% endfor %}
            </td>
        </table>
    </div>

{% endblock %}

templates/question.html
{% extends "include/base.html" %}
{% load static %}


{% block content %}

    {% include "include/main_question.html" with answer_question_block=main %}
    <hr>
    <h3><p class="fst-italic">Answers Block</p></h3>
    <br>
    {% for answer_question_block in page %}
        {% include "include/question_base.html" %}
    {% endfor %}

    {% include "include/pagination.html" %}
    {% if user.is_authenticated %}
        {% include "include/answer_text_area_and_answer_btn.html" %}
    {% endif %}
{% endblock content %}
{% block like_js %}
    <script src="{% static 'js/like.js' %}"></script>
{% endblock %}

templates/settings.html
{% extends 'include/base.html' %}

{% block content %}
    {% include "include/settings_forms.html" %}
{% endblock content %}

templates/signup.html
{% extends 'include/base.html' %}

{% block content %}
    {% include 'include/signup_forms.html' %}
{% endblock content %}

templates/tag_index.html
{% extends "include/base.html" %}
{% load static %}

{% block content %}
    {% include "include/tag_main_column_header.html" %}

    {% for answer_question_block in page %}
        {% include "include/question_base.html" %}
    {% endfor %}

    {% include "include/pagination.html" %}
{% endblock content %}
{% block like_js %}
    <script src="{% static 'js/like.js' %}"></script>
{% endblock %}